# =============================================================================
# miCCI v1.0.0 — Stage 1 runner: COMPUTE PREDICTIONS  (long-running, ~16h)
# -----------------------------------------------------------------------------
# Run this script ONCE on the full Mannheim cohort. It produces:
#   <OUTPUT_DIR>/predictions.parquet   (one row per encounter, all strategies)
#   <OUTPUT_DIR>/run_manifest.json     (parameters, runtime, version, seeds)
#
# After this is done you NEVER need to run it again unless the cohort changes.
# All plots and tables are regenerated by Stage 2 (scripts/02_run_report.R)
# from the predictions.parquet artefact.
# =============================================================================

DATA_PATH   <- "A:/HLZ/Projekt/2025/comorbidity_gaetan/comorbidity_diagnoses_only_pseudonym.parquet"
OUTPUT_DIR  <- "A:/HLZ/Promotionen/Gaetan Kamdje Wabo/Results CCI Model v050"
SAMPLE_SIZE <- NULL    # set to e.g. 5000L for a smoke test, NULL for full run

if (requireNamespace("miCCI", quietly = TRUE)) {
  library(miCCI)
} else if (file.exists("DESCRIPTION")) {
  devtools::load_all(".")
} else {
  stop("miCCI is not installed and DESCRIPTION not found in the working ",
       "directory. Either run `devtools::install('.')` from the miCCI ",
       "folder, or setwd() into it and try again.")
}
library(data.table)

cat(strrep("=", 64), "\n")
cat("miCCI v1.0.0 — Stage 1: compute_predictions\n")
cat("Data:   ", DATA_PATH, "\n")
cat("Output: ", OUTPUT_DIR, "\n")
cat("Sample: ", ifelse(is.null(SAMPLE_SIZE), "FULL", as.character(SAMPLE_SIZE)), "\n")
cat(strrep("=", 64), "\n\n")

res <- compute_predictions(
  data_path   = DATA_PATH,
  output_dir  = OUTPUT_DIR,
  sample_size = SAMPLE_SIZE,
  mi_m        = 20L,
  bayes_draws = 25L,
  sl_cv_folds = 10L,
  seed        = 42L
)

cat("\nWritten files:\n")
print(list.files(OUTPUT_DIR, full.names = TRUE))
cat("\nNext: Rscript scripts/02_run_report.R\n")
